// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace CallCenterServer.Migrations {
    [DbContext(typeof(SQLiteDBContext))]
    [Migration("20200911090205_InitialCreate")]
    partial class InitialCreate
    {
        /// <summary>
        /// Method to make database migration if not exist
        /// </summary>
        /// <param name="modelBuilder">A builder providing a fluentish API for building MigrationOperations</param>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");
#pragma warning restore 612, 618
        }
    }
}
